---
title: "Gov 50 Final Project"
author: "Samantha Williams"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

Does the Supreme Court scrutinize the constitutionality of all legislative issue areas equally? In my study, I plan to examine if the Supreme Court is more likely to evaluate the constitutionality of certain statutory issue areas as compared to others. I hypothesize that the Supreme Court is more likely to evaluate the constitutionality of statutory provisions regarding equality –civil rights and discrimination– than to rule upon other provisions. In the ruling of United States v. Carolene Products in 1938, the Supreme Court established that it would no longer subject economic provision, for example, to the heightened scrutiny designed to protect “discrete and insular minorities.” I am interested to know whether this shift in judicial philosophy is observable in the dataset when comparing data before and after 1938. I will use Keith Whittington’s Judicial Review of Congress dataset found in the appendix of his book, Repugnant Laws: Judicial Review of Acts of Congress from the Founding to the Present (Lawrence: University Press of Kansas, 2019). The data consists of 1308 cases decided by the Supreme Court from its founding through the October 2017 term. The cases are organized into six issue areas: due process (coded =1), substantive rights (=2), equality (=3), economic (=4), federalism (=5), and separation of powers (=6). The explanatory variable of interest is the year with the data (bisected before and after 1938). My outcome variable of interest is the proportion of instances of the Court evaluating ‘equality’ cases. If I observe a higher proportion of instances of the Court evaluating ‘equality’ cases relative to the five other issue areas after 1938, this would provide support for my hypothesis. If I observe a higher proportion of instances of the Court evaluating non-’equality’ cases, especially economic cases, this would provide evidence against my hypothesis and the judicial promise of Carolene Products Footnote 4. When I run a regression to analyze the relationship between the year (before or after 1938) and the proportion of instances where the Supreme Court evaluated 'equality' cases, a positive, significant coefficient would indicate support for my hypothesis.
